# Семинар 1 - numpy, pandas

## 1. Numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [9]:
vec = np.array([[1., 2.5], [3., 4.], [5, 6]], dtype = float)
vec

array([[1. , 2.5],
       [3. , 4. ],
       [5. , 6. ]])

С чем мы работаем?

In [3]:
vec.dtype

dtype('float64')

In [10]:
type(vec)

numpy.ndarray

Размер массива и число осей:

In [7]:
vec.shape

(3, 2)

In [12]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [10]:
np.sum(vec)

21.5

In [11]:
vec.sum()

21.5

In [12]:
vec

array([[1. , 2.5],
       [3. , 4. ],
       [5. , 6. ]])

In [13]:
np.sum(vec, axis=0)

array([ 9. , 12.5])

In [14]:
np.sum(vec, axis=1)

array([ 3.5,  7. , 11. ])

In [16]:
vec.max(axis=0)

array([5., 6.])

Транспонируем массив:

In [17]:
vec.T

array([[1. , 3. , 5. ],
       [2.5, 4. , 6. ]])

In [18]:
vec.transpose()

array([[1. , 3. , 5. ],
       [2.5, 4. , 6. ]])

Обратите внимание, что переменная `vec` не поменялась!

In [19]:
vec 

array([[1. , 2.5],
       [3. , 4. ],
       [5. , 6. ]])

Индексирование:

In [20]:
vec[:, 1]

array([2.5, 4. , 6. ])

In [21]:
vec[2, :]

array([5., 6.])

In [22]:
vec[:2, 1]

array([2.5, 4. ])

In [23]:
vec[::2, :]

array([[1. , 2.5],
       [5. , 6. ]])

In [26]:
a = (vec % 2 == 0)

In [27]:
a

array([[False, False],
       [False,  True],
       [False,  True]])

In [30]:
vec[vec < 2] = -np.inf

In [31]:
vec

array([[-inf,  2.5],
       [ 3. ,  4. ],
       [ 5. ,  6. ]])

Иногда бывает полезно создавать специфичные массивы:

In [ ]:
np.array([[0,0,0], [0,0,0]])

In [37]:
np.zeros((10000, 3000))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
5.4 * np.ones((3, 2))

array([[5.4, 5.4],
       [5.4, 5.4],
       [5.4, 5.4]])

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

И, наконец - арифметические операции!

In [40]:
vec + 1

array([[-inf,  3.5],
       [ 4. ,  5. ],
       [ 6. ,  7. ]])

In [41]:
vec * 2

array([[-inf,   5.],
       [  6.,   8.],
       [ 10.,  12.]])

In [42]:
vec ** 2

array([[  inf,  6.25],
       [ 9.  , 16.  ],
       [25.  , 36.  ]])

In [44]:
vec[0,0] = 0

In [45]:
vec + vec ** 2

array([[ 0.  ,  8.75],
       [12.  , 20.  ],
       [30.  , 42.  ]])

In [48]:
(vec * vec == vec ** 2)

True

In [49]:
np.sin(vec)

array([[ 0.        ,  0.59847214],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

**Задание 1.** Напишите функцию `matrix_mult` (не используя `np.dot` или `np.matmul`)
$$
[AB]_{ij} = \sum\limits_{k}A_{ik} B_{kj}
$$

In [50]:
def matrix_mult(A, B):
  # YOUR CODE HERE
  # A \in [M x N], B \in [N, K]
    # C \in [M x K]
    assert A.shape[1] == B.shape[0]
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i, j] = np.sum(A[i, :] * B[:, j])
    return C

In [65]:
# Test
A = np.array(range(10000)).reshape(100,100)
B = np.array(range(10000)).reshape(100,100)
assert (matrix_mult(A, B) == np.dot(A, B)).all()

In [66]:
(A @ B == np.dot(A, B)).all()

True

**Задание 2.** Напишите функцию `negative_maker`, которая принимает на вход 2 числа `a`, `b` и массив `X` и умножает все элементы `X` котрые лежат в интервале `[a, b]` на `-1`

In [67]:
def negative_maker(X, a, b):
   # YOUR CODE HERE
    mask = (X >= a) & (X <= b)
    X[mask] *= -1
    return X

In [68]:
# test
test = np.array(range(9)).reshape(3,3)
assert (negative_maker(test, -1, 3) == np.array([[ 0, -1, -2], [-3,  4,  5], [ 6,  7,  8]])).all()

Почему вообще используют `numpy`?

In [69]:
%%time
C = matrix_mult(A, B)

CPU times: user 63.3 ms, sys: 2.76 ms, total: 66 ms
Wall time: 65.5 ms


In [70]:
%%time
C = A @ B

CPU times: user 2.1 ms, sys: 650 µs, total: 2.75 ms
Wall time: 1.26 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

## 2. Pandas
![alt text](https://media0.giphy.com/media/fAaBpMgGuyf96/giphy.gif)

- документация: http://pandas.pydata.org/pandas-docs/stable/
- 10 minutes to pandas: https://pandas.pydata.org/pandas-docs/stable/10min.html
- Pandas Tutorial: DataFrames in Python: https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python
- Cheet Sheet: https://www.analyticsvidhya.com/blog/2015/07/11-steps-perform-data-analysis-pandas-python/
- Visualization: http://pandas.pydata.org/pandas-docs/stable/visualization.html

Будем работать с данными, собранными благодаря опросу студентов математического курса средней школы в Португалии (возраст - от 15 до 22 лет). Они находятся в файле ["math_students.csv"](https://drive.google.com/file/d/1RuzDsF8YKCDMVmpkBfjudHd9JALUp3yc/view?usp=sharing). 

 Целевой переменной является итоговая оценка студента за курс.

In [72]:
import matplotlib.pyplot as plt
import pandas as pd

# магическая функция, позволяющая выводить графики прямо в ноутбук
%matplotlib inline

In [73]:
# если данные и ноутбук находятся в разных папках, то для загрузки файла помимо названия необходимо также прописать путь к нему
# .csv - текстовый файл для представления табличных данных, разделенных каким-то символом. В данном случае - запятой
data = pd.read_csv('math_students.csv', delimiter=',')

# функция .head(n) выводит первые n строк таблицы (по умолчанию n=5)
data.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'math_students.csv'

Итак, всего объектов 395, а признаков - 32 (учитываем, что один из столбцов - это целевая переменная). Все признаки имеют разную природу. Вот их более подробная расшифровка:

 - school - тип школы ("GP" - Gabriel Pereira или "MS" - Mousinho da Silveira)
 - sex - пол ("F" - female или "M" - male)
 - age - возраст (от 15 до 22)
 - address - откуда студент ("U" - urban или "R" - rural)
 - famsize - размер семьи ("LE3" - меньше или равно 3 или "GT3" - больше 3)
 - Pstatus - в каких отношениях родители ("T" - живут вместе "A" - раздельно)
 - Medu - образование матери (0 - никакого,  1 - начальное образование (4 класса), 2 – от 5 до 9 классов, 3 – среднеспециальное или 4 – высшее)
 - Fedu - образование отца (0 - никакого,  1 - начальное образование (4 класса), 2 – от 5 до 9 классов, 3 – среднеспециальное или 4 – высшее)
 - Mjob - работа матери ("teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
 - Fjob - работа отца ("teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
 - reason - причина выбора школы (близко к дому — "home", репутация школы — "reputation", предпочтение некоторым предметам - "course" или "other")
 - guardian - опекун ("mother", "father" или "other")
 - traveltime - время от дома до школы (1 - меньше 15 мин., 2 - 15 до 30 мин., 3 - 30 мин. до 1 часа, или 4 - больше 1 часа)
 - studytime - количество часов обучения в неделю (1 - меньше 2 часов, 2 - от 2 до 5 часов, 3 - от 5 до 10 часов, или 4 - больше 10 часов)
 - failures - количество ранее не сданных предметов (n if 1 <= n < 3, else 4)
 - schoolsup - дополнительные занятия (yes or no)
 - famsup - помощь от семьи при выполнении заданий (yes or no)
 - paid - дополнительные платные занятия (yes or no)
 - activities - внеклассная деятельность (yes or no)
 - nursery - посещал детский сад (yes or no)
 - higher - желание высшего образования (yes or no)
 - internet - домашний интернет (yes or no)
 - romantic - состоит в романтических отношениях (yes or no)
 - famrel - насколько хороши отношения в семье (от 1 - очень плохие до 5 - превосходные)
 - freetime - наличие свободного времени после школы (от 1 - очень мало до 5 - очень много)
 - goout - гуляет с друзьями (от 1 - редко до 5 - очень часто)
 - Dalc - употребление алкоголя в будние дни (от 1 - очень редко до 5 - очень часто)
 - Walc - употребление алкоголя в выходные (от 1 - очень редко до 5 - очень часто)
 - health - текущее состояние здоровья (от 1 - очень плохое до 5 - очень хорошее)
 - absences - количество школьных пропусков (от 0 до 93)
 - G1 - оценка за первый семестр (от 0 до 20)
 - G2 - оценка за второй семестр (от 0 до 20)
 - G3 - итоговая оценка (от 0 до 20)

 ---

 Для вывода названий всех признаков есть специальная функция:

In [64]:
data.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [65]:
data.G3 

0       6
1       6
2      10
3      15
4      10
       ..
390     9
391    16
392     7
393    10
394     9
Name: G3, Length: 395, dtype: int64

In [ ]:
data['G3']

0       6
1       6
2      10
3      15
4      10
       ..
390     9
391    16
392     7
393    10
394     9
Name: G3, Length: 395, dtype: int64

In [67]:
data[['G3']]

G3
0     6
1     6
2    10
3    15
4    10
..   ..
390   9
391  16
392   7
393  10
394   9

[395 rows x 1 columns]

In [69]:
data.iloc[:10, 10]

0        course
1        course
2         other
3          home
4          home
5    reputation
6          home
7          home
8          home
9          home
Name: reason, dtype: object